from PyQt5 import QtCore, QtWidgets

# TODO Input callbacks
# TODO Input typechecking, if incorrect input highlight red with modal message?
# TODO Show webcam output from certain port?


class Window:
    def __init__(self):
        self.main_window = QtWidgets.QMainWindow()
        self.main_window.setObjectName("main_window")
        self.main_window.resize(350, 300)
        self.centralwidget = QtWidgets.QWidget(self.main_window)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.actions = QtWidgets.QWidget()
        self.actions.setObjectName("actions")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.actions)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.actions)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 308, 231))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_6)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboBox_2 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.actions, "")
        self.settings = QtWidgets.QWidget()
        self.settings.setObjectName("settings")
        self.formLayout_2 = QtWidgets.QFormLayout(self.settings)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.settings)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.gst_ip = QtWidgets.QLineEdit(self.settings)
        self.gst_ip.setObjectName("gst_ip")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.gst_ip)
        self.label_5 = QtWidgets.QLabel(self.settings)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.gst_port = QtWidgets.QLineEdit(self.settings)
        self.gst_port.setObjectName("gst_port")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.gst_port)
        self.tabWidget.addTab(self.settings, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.main_window.setCentralWidget(self.centralwidget)
        self.actionSettings = QtWidgets.QAction(self.main_window)
        self.actionSettings.setObjectName("actionSettings")

        self.retranslate_ui()
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(self.main_window)

    def retranslate_ui(self):
        _translate = QtCore.QCoreApplication.translate
        self.main_window.setWindowTitle(_translate("MainWindow", "Skeyes"))
        self.label_3.setText(_translate("MainWindow", "Feature"))
        self.label_6.setText(_translate("MainWindow", "Action"))
        self.label.setText(_translate("MainWindow", "Windows"))
        self.comboBox.setCurrentText(_translate("MainWindow", "Pause"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Pause"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Ignore"))
        self.label_2.setText(_translate("MainWindow", "Gutters"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Pause"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Ignore"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.actions), _translate("MainWindow", "Actions"))
        self.label_4.setText(_translate("MainWindow", "QGroundControl IP:"))
        self.gst_ip.setText(_translate("MainWindow", "localhost"))
        self.label_5.setText(_translate("MainWindow", "Streaming Port:"))
        self.gst_port.setText(_translate("MainWindow", "5600"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings), _translate("MainWindow", "Settings"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))

    def show(self):
        self.main_window.show()
